# Name of the stage that will appear in GitHub actions.
name: Build

# Controls when the workflow will run.
on:
  # Triggers the workflow when a commit is pushed.
  push:
    branches:
      - main

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # Windows - Build
  Windows:
    # The type of runner that the job will run on
    runs-on: windows-2019
    continue-on-error: false
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: Scripts/BuildMachine/BuildMachine-Windows-Build.bat
        
      - name: Archive Windows Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Binaries
          path: |
            Binaries/**
          
  # Linux - Build
  Linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          chmod +x Scripts/BuildMachine/BuildMachine-Linux-Build.sh
          Scripts/BuildMachine/BuildMachine-Linux-Build.sh
        
      - name: Archive Linux Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linux-Binaries
          path: |
            Binaries/**
       
#  # Mac - Build
#  Mac:
#    # The type of runner that the job will run on
#    runs-on: macos-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#        
#      - name: Build
#        working-directory: ${{env.GITHUB_WORKSPACE}}
#        run: |
#          chmod +x Scripts/BuildMachine/BuildMachine-Mac-Build.sh
#          Scripts/BuildMachine/BuildMachine-Mac-Build.sh
#
#      - name: Archive Mac Artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: Mac-Binaries
#          path: |
#            Binaries/**
#