# Name of the stage that will appear in GitHub actions.
name: Windows Build

# Controls when the workflow will run.
on:
  # Triggers the workflow when a commit is pushed.
  push:
    branches:
      - main

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # Windows - Build
  Windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    continue-on-error: false
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: Scripts/BuildMachine/BuildMachine-Windows-Build.bat
        
      - name: Archive Windows Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Binaries
          path: |
            Binaries/**